# .github/workflows/main.yml
name: Pipeline CI/CD

# Se déclenche à chaque push sur la branche main
on:
  push:
    branches: [ main ]

jobs:
  # ÉTAPE 1 : Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install -r requirements.txt pytest

      - name: Lancer les tests
        run: pytest test_app.py

  # ÉTAPE 2 : Build Docker
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Construire l'image Docker
        run: docker build -t mon-app .

      - name: Vérifier l'image
        run: docker images
